### ISSUE TITLE
Add icon for related .SFO file

### ISSUE THREAD

**Issue by WanderMax** [darkautism/KautismSFOEditor#3]
Could you please add icon for the related .SFO files?
Now the .SFO files have no related icon.

**Comment by darkautism** [comment]
Add icon support. 0f4677b2f5be1e142468ecdbdbd4a820bbd79062

**Comment by WanderMax** [comment]
any plan to integrate the .ico file into main .exe file?
any plan to add language switch into the setting page?

**Comment by darkautism** [comment]
1. 4dfc0be5b46fc303f21777d29654020908d1399e
2. Maybe next release.
