### ISSUE TITLE
修改後制成ISO无法使Cobra混合系统辨识

### ISSUE THREAD

**Issue by Raiyou** [darkautism/KautismSFOEditor#6]
碰了一下午灰後从HEX EDITOR发现问题所在
在v1.1.3与v1.1.4中 更改sfo信息会使数据偏移 
如此产生的sfo在制作为ISO镜像後将无法受系统辨识呈“资料毁损”
估计是系统对ISO镜像的标准比较严格 
v1.1.0与v1.1.1一切正常 但有个小问题是TITLE信息改短後剩余数据没有填00
不过这不影响正确ISO的制作

**Comment by darkautism** [comment]
你好，我已經沒有PS3可以讓我開發測試了，可以的話發送原文件與修改過的文件
我會較為容易除錯。

**Comment by Raiyou** [comment]
http://www58.zippyshare.com/v/JKozGUFN/file.html

**Comment by darkautism** [comment]
Should fix at e2350615bad3cf2842bf4eb4f104e2367e4dc713 commit
